-- =====================================================
-- FRESH INSTALLATION - EVENT MANAGEMENT SYSTEM
-- Không có migration, bắt đầu với schema mới
-- =====================================================

-- PHẦN 1: TẠO TABLE EVENTS
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_date DATE NOT NULL,
  target_checkins INTEGER DEFAULT 0,
  description TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id)
);

-- Indexes cho events table
CREATE INDEX IF NOT EXISTS idx_events_status ON public.events(status);
CREATE INDEX IF NOT EXISTS idx_events_date ON public.events(event_date);

-- Enable RLS cho events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- RLS Policies cho events
CREATE POLICY "Admin can manage events"
  ON public.events
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.app_users
      WHERE app_users.id = auth.uid()
      AND app_users.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.app_users
      WHERE app_users.id = auth.uid()
      AND app_users.role = 'admin'
    )
  );

CREATE POLICY "All authenticated can view events"
  ON public.events
  FOR SELECT
  TO authenticated
  USING (true);

-- PHẦN 2: MODIFY TABLE EVENT_CHECKINS
-- Thay đổi event_id từ TEXT sang BIGINT với foreign key

-- Drop column cũ
ALTER TABLE public.event_checkins
DROP COLUMN IF EXISTS event_id;

-- Add column mới với foreign key
ALTER TABLE public.event_checkins
ADD COLUMN event_id BIGINT REFERENCES public.events(id);

-- Tạo index cho event_id
CREATE INDEX IF NOT EXISTS idx_checkins_event_id
ON public.event_checkins(event_id);

-- PHẦN 3: UPDATE FUNCTION get_checkin_stats
DROP FUNCTION IF EXISTS get_checkin_stats(TEXT);

CREATE OR REPLACE FUNCTION get_checkin_stats(p_event_id BIGINT DEFAULT NULL)
RETURNS TABLE (
  total_checkins BIGINT,
  today_checkins BIGINT,
  last_hour_checkins BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT as total_checkins,
    COUNT(*) FILTER (WHERE checked_in_at::date = CURRENT_DATE)::BIGINT as today_checkins,
    COUNT(*) FILTER (WHERE checked_in_at > NOW() - INTERVAL '1 hour')::BIGINT as last_hour_checkins
  FROM public.event_checkins
  WHERE p_event_id IS NULL OR event_id = p_event_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- PHẦN 4: TẠO FUNCTION EVENT STATISTICS
CREATE OR REPLACE FUNCTION get_event_stats(p_event_id BIGINT DEFAULT NULL)
RETURNS TABLE (
  event_id BIGINT,
  event_name TEXT,
  total_checkins BIGINT,
  target_checkins INTEGER,
  completion_percentage NUMERIC,
  today_checkins BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id as event_id,
    e.event_name,
    COUNT(ec.id)::BIGINT as total_checkins,
    e.target_checkins,
    CASE
      WHEN e.target_checkins > 0
      THEN ROUND((COUNT(ec.id)::NUMERIC / e.target_checkins::NUMERIC * 100), 2)
      ELSE 0
    END as completion_percentage,
    COUNT(ec.id) FILTER (WHERE ec.checked_in_at::date = CURRENT_DATE)::BIGINT as today_checkins
  FROM public.events e
  LEFT JOIN public.event_checkins ec ON e.id = ec.event_id
  WHERE (p_event_id IS NULL OR e.id = p_event_id)
  GROUP BY e.id, e.event_name, e.target_checkins;
END;
$$;

-- PHẦN 5: ENABLE REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE public.events;

-- PHẦN 6: TRIGGER CHO AUTO-UPDATE updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_events_updated_at
  BEFORE UPDATE ON public.events
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

-- PHẦN 7: TẠO SAMPLE EVENT (Optional - để test)
INSERT INTO public.events (event_name, event_date, target_checkins, description)
VALUES
  ('Grand Opening 2024', '2024-12-25', 500, 'Sự kiện khai trương'),
  ('Year End Party', '2024-12-31', 1000, 'Tiệc cuối năm công ty');

-- =====================================================
-- VERIFY INSTALLATION
-- =====================================================

-- Check tables structure
SELECT
    table_name,
    column_name,
    data_type
FROM
    information_schema.columns
WHERE
    table_name IN ('events', 'event_checkins')
    AND table_schema = 'public'
ORDER BY
    table_name, ordinal_position;

-- Test functions
SELECT * FROM get_event_stats()